services:
  - type: web
    name: job-tracker
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && cd ../frontend && npm install && npm run build && cd ../backend && flask db upgrade
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-tracker-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: ADZUNA_APP_ID
        sync: false
      - key: ADZUNA_API_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: NODE_VERSION
        value: "20"

databases:
  - name: job-tracker-db
    plan: free
    databaseName: job_tracker
